# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
resultado = np.all(a != 0)
print(f"Arreglo: {a}")
print(f"¿Ningún elemento es cero? {resultado}")

Arreglo: [1 2 3 4]
¿Ningún elemento es cero? True


In [3]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
resultado = np.any(a != 0)
print(f"Arreglo: {a}")
print(f"¿Contiene algún elemento distinto de cero? {resultado}")

Arreglo: [0 0 2 0]
¿Contiene algún elemento distinto de cero? True


In [4]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
tiene_nan = np.isnan(a)
tiene_inf = np.isinf(a)
print(f"Arreglo: {a}")
print(f"Contiene NaN: {tiene_nan}")
print(f"Contiene Inf: {tiene_inf}")
print(f"¿Tiene valores infinitos o NaN? {np.any(tiene_nan | tiene_inf)}")

Arreglo: [ 1.  2. nan inf]
Contiene NaN: [False False  True False]
Contiene Inf: [False False False  True]
¿Tiene valores infinitos o NaN? True


In [5]:
# ejercicio 4
a = np.array([1, 2, np.inf])
resultado = np.isinf(a)
print(f"Arreglo: {a}")
print(f"Contiene infinitos: {resultado}")
print(f"¿Algún valor infinito? {np.any(resultado)}")

Arreglo: [ 1.  2. inf]
Contiene infinitos: [False False  True]
¿Algún valor infinito? True


In [6]:
# ejercicio 5
a = np.array([1, np.nan, 3])
resultado = np.isnan(a)
print(f"Arreglo: {a}")
print(f"Contiene NaN: {resultado}")
print(f"¿Algún valor NaN? {np.any(resultado)}")

Arreglo: [ 1. nan  3.]
Contiene NaN: [False  True False]
¿Algún valor NaN? True


In [7]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
print(f"a = {a}")
print(f"b = {b}")
print(f"a > b  = {a > b}")
print(f"a >= b = {a >= b}")
print(f"a < b  = {a < b}")
print(f"a <= b = {a <= b}")

a = [1 3 5]
b = [2 3 4]
a > b  = [False False  True]
a >= b = [False  True  True]
a < b  = [ True False False]
a <= b = [ True  True False]


In [8]:
# ejercicio 7
a = np.array([1, 7, 13, 105])
print(f"Arreglo: {a}")
print(f"Memoria ocupada: {a.nbytes} bytes")

Arreglo: [  1   7  13 105]
Memoria ocupada: 32 bytes


In [9]:
# ejercicio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)
print(f"10 ceros: {ceros}")
print(f"10 unos:  {unos}")
print(f"10 cincos: {cincos}")

10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 unos:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10 cincos: [5 5 5 5 5 5 5 5 5 5]


In [10]:
# ejercicio 9
a = np.arange(30, 71)
print(f"Enteros entre 30 y 70: {a}")

Enteros entre 30 y 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
# ejercicio 10
a = np.arange(30, 71, 2)
print(f"Pares entre 30 y 70: {a}")

Pares entre 30 y 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
# ejercicio 11
I = np.eye(3)
print("Matriz identidad 3x3:")
print(I)

Matriz identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# ejercicio 12
r = np.random.rand()
print(f"Número aleatorio entre 0 y 1: {r}")

Número aleatorio entre 0 y 1: 0.28544383294397035


In [14]:
# ejercicio 13
a = np.random.randn(15)
print(f"15 números de distribución normal estándar:\n{a}")

15 números de distribución normal estándar:
[ 1.51262446  0.46192775 -1.5022356  -2.24815664  1.51712267 -0.68027401
  0.23264698  0.17130343 -0.14533227  1.71951859 -0.05493069 -0.58168746
  0.30278813 -1.37612109 -1.376632  ]


In [15]:
# ejercicio 14
a = np.arange(15, 56)
print(f"Arreglo completo: {a}")
print(f"Excepto primero y último: {a[1:-1]}")

Arreglo completo: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Excepto primero y último: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [16]:
# ejercicio 15
a = np.linspace(5, 50, 10)
print(f"Vector de 10 valores equidistribuidos entre 5 y 50:\n{a}")

Vector de 10 valores equidistribuidos entre 5 y 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [17]:
# ejercicio 16
a = np.arange(0, 21)
print(f"Original: {a}")
a[(a >= 9) & (a <= 15)] *= -1
print(f"Modificado (signo cambiado del 9 al 15): {a}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modificado (signo cambiado del 9 al 15): [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [18]:
# ejercicio 17
a = np.array([1, 2, 3])
l = a.tolist()
print(f"Arreglo: {a}")
print(f"Lista de Python: {l}")

Arreglo: [1 2 3]
Lista de Python: [1, 2, 3]


In [19]:
# ejercicio 18
l = [1, 2, 3]
a = np.array(l)
print(f"Lista: {l}")
print(f"Arreglo NumPy: {a}")

Lista: [1, 2, 3]
Arreglo NumPy: [1 2 3]


In [20]:
# ejercicio 19
m = np.array([[1, 2], [3, 4]])
pares = m % 2 == 0
print(f"Matriz original:\n{m}")
print(f"Matriz booleana (pares):\n{pares}")
print(f"Valores pares: {m[pares]}")

Matriz original:
[[1 2]
 [3 4]]
Matriz booleana (pares):
[[False  True]
 [False  True]]
Valores pares: [2 4]


In [21]:
# ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print(f"Matriz:\n{m}")
print(f"Filas: {filas}, Columnas: {columnas}")

Matriz:
[[1 2 3]
 [4 5 6]]
Filas: 2, Columnas: 3
